#自动化部署
stages:
  - build
  - deploy

#build过程
build:
   stage: build
   image: node:9.4.0
   cache:
     paths:
     - node_modules/
   script:
   - npm install
   - npm run build
   artifacts:
     paths:
     - dist
   only:
   - master

#deploy过程
deploy:
    stage: deploy
    image: alpine:latest

    script:
      - mv dist/* /home/wwwroot/www.ohmynest.com
    only:
      - master
    tags:
      - devops
