#自动化部署
#2018-12-30 01:49:07
stages:
  - build
  - develop
  - test
  - deploy

#build过程
build:
   stage: build
   image: node:9.4.0
   cache:
     paths:
     - node_modules/
   script:
   - npm install
   - npm run build:dev
   artifacts:
     paths:
     - dist
   only:
   - master

build:
   stage: build
   image: node:9.4.0
   cache:
     paths:
     - node_modules/
   script:
   - npm install
   - npm run build:test
   artifacts:
     paths:
     - dist
   only:
   - test
build:
   stage: build
   image: node:9.4.0
   cache:
     paths:
     - node_modules/
   script:
   - npm install
   - npm run build:prod
   artifacts:
     paths:
     - dist
   only:
   - release
#test
develop:
   stage: develop
   image: alpine:latest
   script:
     - rm -Rf /home/wwwroot/www.dev.ohmynest.com/*
     - cp -Rf dist/* /home/wwwroot/www.dev.ohmynest.com/
   only:
     - master
   tags:
     - devops

#test
test:
    stage: test
    image: alpine:latest
    script:
      - rm -Rf /home/wwwroot/www.test.ohmynest.com/*
      - cp -Rf dist/* /home/wwwroot/www.test.ohmynest.com/
    only:
      - test
    tags:
      - devops

#deploy过程
deploy:
    stage: deploy
    image: alpine:latest
    script:
      - rm -Rf /home/wwwroot/www.ohmynest.com/*
      - cp -Rf dist/* /home/wwwroot/www.ohmynest.com/
    only:
      - release
    tags:
      - devops
