#自动化部署
#2018-12-30 01:49:07
stages:
  - build
  - deploy

#build过程
build:
   stage: build
   image: node:9.4.0
   cache:
     paths:
     - node_modules/
   script:
   - npm install
   - npm run dev
   artifacts:
     paths:
     - dist
   only:
   - master

#deploy过程
deploy:
    stage: deploy
    image: alpine:latest
    script:
      - rm -Rf /home/wwwroot/www.ohmynest.com/*
      - cp -Rf dist/* /home/wwwroot/www.ohmynest.com/
    only:
      - master
    tags:
      - devops
